version: 0.1
phases:
  build:
    commands:
      - mvn clean
      - mvn install
      - mvn package
  post_build:
    commands:
      - mv target/LoginApp*.war target/loginapp.war
      - echo "******** Uploading to S3 ********"
      - aws s3 sync target/*.war s3://elanrepo/tomcat/wars
artifacts:
  files:
    - target/*.war
